services:
  - type: web
    name: crops  # This is the name of your service
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn crop_recommendation.wsgi"  # Replace 'your_project_name' with the actual project name
    autoDeploy: true
    plan: free
