# Generated by Django 5.0.7 on 2024-10-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='K',
            field=models.FloatField(verbose_name='Potassium (K)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='N',
            field=models.FloatField(verbose_name='Nitrogen (N)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='P',
            field=models.FloatField(verbose_name='Phosphorus (P)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop_name',
            field=models.CharField(max_length=100, verbose_name='Crop Name'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='humidity',
            field=models.FloatField(verbose_name='Humidity (%)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='pH',
            field=models.FloatField(verbose_name='pH Level'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='rainfall',
            field=models.FloatField(verbose_name='Rainfall (mm)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='temperature',
            field=models.FloatField(verbose_name='Temperature (°C)'),
        ),
    ]
